### ISSUE TITLE
Quarkchain -ETHhash

### ISSUE THREAD

**Issue by frode88** [EasyX-Community/EasyNOMP-old#87]
Hi. 
Its possibel for this pool to work with Quarkchain coin?
Thank you.

**Comment by mooleshacat** [comment]
I will add it to the pile of algo's that probably will not end up getting completed as I am not capable of adding in algos yet. That is the reason all of them are marked as "low priority".

I have other bigger issues that I _can_ work on though :+1:

**Comment by sniper-noob** [comment]
@leshacat Ok, thank you:)
